version: '3'

# include:
  # - docker-compose.rpc.yml

services:
  apps:
    image: laravel_app_postgresdb_dev:1.0
    container_name: apps_dev
    env_file:
      - dev.env
    volumes:
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./apps:/app
    command: sh run.sh
    networks:
      - app_dev
    depends_on:
      - postgresdb
      - redis
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 512M

  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy_dev
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./apps:/app
      - caddy_data:/data
    networks:
      - app_dev
    depends_on:
      - apps
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 128M

  postgresdb:
    image: postgres:16.2-alpine3.19
    container_name: postgres_dev
    env_file:
      - dev.env
    volumes:
      - postgresdb_data:/var/lib/postgresql
    networks:
      - app_dev
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 512M

  pgweb:
    image: sosedoff/pgweb:0.14.3
    container_name: pgweb_dev
    env_file:
      - dev.env
    networks:
      - app_dev
    ports:
      - "8081:8081"
    volumes:
      - ./certs:/certs
    depends_on:
      - postgresdb
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 64M

  buggregator:
    image: ghcr.io/buggregator/server:1.5.0
    container_name: buggregator_dev
    networks:
      - app_dev
    ports:
      - "8000:8000"
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:7.2-alpine
    container_name: redis_dev
    command: [
      "redis-server",
      "--appendonly",
      "yes",
      "--requirepass",
      "L2hgheewayei5eechW2"
    ]
    volumes:
      - redis_data:/data
    networks:
      - app_dev
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      memlock: -1

  minio:
    image: minio/minio:RELEASE.2024-01-31T20-20-33Z
    container_name: minio_dev
    command: [
      "server",
      "--console-address",
      ":9001",
      "/data"
    ]
    env_file:
      - dev.env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app_dev
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  caddy_data:
    name: caddy_dev_data
  redis_data:
    name: redis_dev_data
  minio_data:
    name: minio_dev_data
  postgresdb_data:
    name: postgresdb_dev_data

networks:
   app_dev:
     driver: bridge
     name: app_dev
